generic-service:
  nameOverride: hmpps-welcome-people-into-prison-ui

  replicaCount: 4

  serviceAccountName: hmpps-welcome-to-prison

  image:
    repository: ghcr.io/ministryofjustice/hmpps-welcome-people-into-prison-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-welcome-to-prison-cert
    v1_2_enabled: true
    v0_47_enabled: false

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_ENABLED: "true"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    ENABLED_PRISONS: 'BFI,BNI,BWI,CDI,DMI,EXI,EYI,HEI,HLI,LCI,LEI,LII,LPI,LWI,MHI,NMI,NWI,PNI,PVI,WCI,WSI,WWI,STI'
    FEMALE_PRISONS: 'STI'
    LOAD_DPR_ON_STARTUP: "true"
  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-welcome-people-into-prison-ui:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
      TAG_MANAGER_CONTAINER_ID: "TAG_MANAGER_CONTAINER_ID"
      TAG_MANAGER_ENVIRONMENT: "TAG_MANAGER_ENVIRONMENT"
      GOOGLE_SERVICE_ACCOUNT_KEY: "GOOGLE_SERVICE_ACCOUNT_KEY"
      GOOGLE_ANALYTICS_ID: "GOOGLE_ANALYTICS_ID"
      NOTIFY_API_KEY: "NOTIFY_API_KEY"
      FEEDBACK_EMAIL: "FEEDBACK_EMAIL"
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

  allowlist:
    groups:
      - internal
      - prisons
      - private_prisons

generic-prometheus-alerts:
  targetApplication: hmpps-welcome-people-into-prison-ui
  alertSeverity: move-a-prisoner-alerts-nonprod

jobs:
  cronspec: "59 * * * *"
