export default {
  arrival: ({
    fromLocationType,
    isCurrentPrisoner = false,
    dateOfBirth = '1970-01-01',
    pncNumber = '01/2345A',
    prisonNumber = 'G0015GF',
    gender = 'MALE',
    firstName = 'Bob',
    lastName = 'Smith',
    date = '2021-09-01',
    potentialMatches = [],
  }) => ({
    id: '11111-11111',
    firstName,
    lastName,
    dateOfBirth,
    pncNumber,
    prisonNumber,
    date,
    gender,
    fromLocation: 'Moorland (HMP & YOI)',
    fromLocationId: 'MDI',
    fromLocationType,
    isCurrentPrisoner,
    potentialMatches,
  }),
  potentialMatch: {
    firstName: 'Sam',
    lastName: 'Smith',
    dateOfBirth: '1970-02-01',
    prisonNumber: 'A1234BC',
    pncNumber: '01/4567A',
    sex: 'MALE',
  },
  prisonTransfer: {
    firstName: 'Karl',
    lastName: 'Offender',
    dateOfBirth: '1985-01-01',
    prisonNumber: 'G0015GD',
    pncNumber: '01/5678A',
    date: '2021-09-01',
    fromLocation: 'Leeds',
    fromLocationType: 'PRISON',
  },
  court: {
    current: {
      id: '00000-22222',
      firstName: 'John',
      lastName: 'Doe',
      dateOfBirth: '1971-01-01',
      prisonNumber: 'G0013AB',
      pncNumber: '01/3456A',
      date: '2021-09-01',
      fromLocation: 'Reading',
      fromLocationType: 'COURT',
      isCurrentPrisoner: true,
      potentialMatches: [
        {
          firstName: 'Sam',
          lastName: 'Smith',
          dateOfBirth: '1970-02-01',
          prisonNumber: 'A1234BC',
          pncNumber: '01/4567A',
          arrivalType: 'FROM_COURT',
        },
      ],
    },
  },
}
