export default {
  okToScan: (prisonerNumber = 'A1234BC') => ({
    prisonerNumber,
    nomisCount: 0,
    dpsCount: 10,
    totalCount: 10,
    positiveCount: 0,
    negativeCount: 10,
    inconclusiveCount: 0,
    annualLimit: 116,
    remainingScans: 106,
    nearingScanLimit: false,
    atScanLimit: false,
    fromScanDate: '2026-01-01',
    toScanDate: '2026-12-31',
    relevantAlerts: [],
    latestScan: { source: 'DPS', scanDate: '2026-09-01', outcomeDescription: 'Negative', scanDetails: null },
  }),
  closeToLimit: (prisonerNumber = 'A1234BC') => ({
    prisonerNumber,
    nomisCount: 0,
    dpsCount: 114,
    totalCount: 114,
    positiveCount: 0,
    negativeCount: 114,
    inconclusiveCount: 0,
    annualLimit: 116,
    remainingScans: 2,
    nearingScanLimit: true,
    atScanLimit: false,
    fromScanDate: '2026-01-01',
    toScanDate: '2026-12-31',
    relevantAlerts: [],
    latestScan: { source: 'DPS', scanDate: '2026-09-01', outcomeDescription: 'Negative', scanDetails: null },
  }),
  withAlert: (prisonerNumber = 'A1234BC') => ({
    prisonerNumber,
    nomisCount: 0,
    dpsCount: 5,
    totalCount: 5,
    positiveCount: 0,
    negativeCount: 5,
    inconclusiveCount: 0,
    annualLimit: 116,
    remainingScans: 111,
    nearingScanLimit: false,
    atScanLimit: false,
    fromScanDate: '2026-01-01',
    toScanDate: '2026-12-31',
    relevantAlerts: [
      {
        id: '1',
        type: 'XRBS',
        typeDescription: 'Security',
        code: 'XIS',
        codeDescription: 'Internal secretor',
      },
    ],
    latestScan: { source: 'DPS', scanDate: '2026-09-01', outcomeDescription: 'Negative', scanDetails: null },
  }),
  withNomisCount: (prisonerNumber = 'A1234BC') => ({
    prisonerNumber,
    nomisCount: 5,
    dpsCount: 8,
    totalCount: 13,
    positiveCount: 0,
    negativeCount: 13,
    inconclusiveCount: 0,
    annualLimit: 116,
    remainingScans: 103,
    nearingScanLimit: false,
    atScanLimit: false,
    fromScanDate: '2026-01-01',
    toScanDate: '2026-12-31',
    relevantAlerts: [],
    latestScan: { source: 'NOMIS', scanDate: '2026-08-15', outcomeDescription: null, scanDetails: 'Negative' },
  }),
  doNotScan: (prisonerNumber = 'A1234BC') => ({
    prisonerNumber,
    nomisCount: 0,
    dpsCount: 116,
    totalCount: 116,
    positiveCount: 0,
    negativeCount: 116,
    inconclusiveCount: 0,
    annualLimit: 116,
    remainingScans: 0,
    nearingScanLimit: false,
    atScanLimit: true,
    fromScanDate: '2026-01-01',
    toScanDate: '2026-12-31',
    relevantAlerts: [],
    latestScan: { source: 'DPS', scanDate: '2026-09-01', outcomeDescription: 'Negative', scanDetails: null },
  }),
}
