apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: wpip-ui-update-events
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.jobs.cronspec | quote }}
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      # Tidy up all jobs after 4 days
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 240
          containers:
            - name: hmpps-welcome-people-into-prison-ui
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: IfNotPresent
              args:
                - node
                - backend/jobs/eventsJob
{{ include "deployment.envs" (index .Values "generic-service") | nindent 12  }}
