---
# Per environment values which override defaults in hmpps-welcome-people-into-prison-ui/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    hosts:
      - welcome-preprod.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://welcome-preprod.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    DPS_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    WELCOME_API_URL: "https://welcome-api-preprod.prison.service.justice.gov.uk"
    BODYSCAN_API_URL: "https://welcome-api-preprod.prison.service.justice.gov.uk"
    HMPPS_COOKIE_NAME: hmpps-session-preprod
    APP_HOSTNAME: welcome-preprod.prison.service.justice.gov.uk
    SYSTEM_PHASE: PRE-PRODUCTION
    CONFIRM_ENABLED: 'true'
    CONFIRM_NO_IDENTIFIERS_ENABLED: 'true'
    CONFIRM_COURT_RETURN_ENABLED: 'false'
    SUPPORTING_MULTITRANSACTIONS_ENABLED: 'true'
    EXPORT_SPREADSHEET_ID: "15tjbOMJUAGSVQ4tpcEi83jWkzkMNrptUH6SC0ZHslqY"
    SERVICE_IS_UNAVAILABLE: "false"
    SHOW_EXPECTED_ARRIVAL_PRISONER_SUMMARY: 'true'
    SHOW_PRISON_TRANSFER_SUMMARY: 'false'
    SHOW_BREADCRUMB: 'true'
    SHOW_RECENT_ARRIVALS: 'true'
