const enum Role {
  PRISON_RECEPTION = 'ROLE_PRISON_RECEPTION',
  ROLE_INACTIVE_BOOKINGS = 'ROLE_INACTIVE_BOOKINGS',
  GLOBAL_SEARCH = 'ROLE_GLOBAL_SEARCH',
  REPORT_USER = 'ROLE_PRISONS_REPORTING_USER',
}

export default Role
